#Create a docker compose file to setup a mysql and wordpress 
container and link them

version: '3.8'
services:
  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: testcloud


  mywordpress:
    image: wordpress
    ports:
      - 8888:80
    links:
      mydb:mysql
...
