#Create a docker compose file to setup a mysql and wordpress 
container and link them

version: '3.8'
services:
  mydb:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: testcloud


  mywordpress:
    image: wordpress
    ports:
      - 8888:80
    links:
      mydb:mysql
...

#To setup the containers from the above file
docker-compose up -d
#To stop all the container of the docker compose file
docker-compose stop
#To start the container
docker-compose start

#To stop and delete
docker-compose down
